name: practicas_as ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.17.6
        with:
          otp-version: 26.2
          rebar3-version: 3.20.0
      - name: Checks
        run: |
          rebar3 dialyzer
          # rebar3 eunit -v
          rebar3 proper -c true --module prop_boolean
          rebar3 cover -m 100
