name: practicas_as ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.17.6
        with:
          otp-version: 26.2
          rebar3-version: 3.20.0
      - name: Checks
        run: |
          rebar3 dialyzer
<<<<<<< HEAD
          rebar3 eunit -v
          rebar3 proper -c true --module prop_boolean,prop_create,prop_manipulating,prop_sorting,prop_db
=======
          # rebar3 eunit -v
<<<<<<< HEAD
          rebar3 proper -c true --module prop_boolean,prop_create,prop_manipulating,prop_sorting
=======
          rebar3 proper -c true --module prop_boolean,prop_echo.erl,prop_positive_echo
>>>>>>> 3485eff (fix: pr comments)
>>>>>>> 662e4b0 (fix: pr comments)
          # rebar3 cover -m 100
